name: dial_picker
description: A simple widget to pick Duration values. Forked with updated dependencies from https://github.com/juliansteenbakker/duration_picker.

version: 1.0.1+1

repository: https://github.com/rilpires/dial_picker

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
